Scanhub UI/issue/33 login functionality
brain-link/scanhub pull request #101
Opened 2024-05-17 16:04 UTC by BenWilhelmUniklinikFreiburg

Please continue work with the updated code to avoid future merge conflicts. Code was tested and should work. A default user needs to be added manually to the database for now. Such a database entry is described in the readme and in defaultuser.txt.

2024-05-22 18:26 UTC, schote requested changes
Thank you @BenWilhelmUniklinikFreiburg for this excellent work! I think it's a great kick-off for the implementation of user management. 

My comments basically refer to one change request we already discussed: Moving the user dal and db to a user manager micro service (the user-login-services) and implement the `get_current_user` as an endpoint which is used in a shared async function. 
I have marked all the files/lines that I think are relevant to this amendment. Happy to help out with this change request.

2024-05-22 18:26 UTC, schote commented on services/base/shared_libs/src/scanhub_libraries/db.py
After discussion we agreed to move the user database and data access layer to the user-login-manager/user-manager.

2024-05-22 18:26 UTC, schote commented on services/base/shared_libs/src/scanhub_libraries/dal.py
After discussion we agreed to move the user database and data access layer to the user-login-manager/user-manager.

2024-05-28 20:17 UTC, schote commented
closes #55

2024-05-31 18:10 UTC, BenWilhelmUniklinikFreiburg commented on services/base/shared_libs/src/scanhub_libraries/security.py
The function get_current_user uses an endpoint now, but keeping it in security.py helps to avoid code duplication.

2024-05-31 18:11 UTC, BenWilhelmUniklinikFreiburg commented on services/acquisition-control/app/main.py
> +    dependencies=[Depends(get_current_user)]
done

2024-06-02 16:53 UTC, schote approved these changes
Thank you @BenWilhelmUniklinikFreiburg!

2024-06-02 16:54 UTC, merged