Sphinx Docu
brain-link/scanhub pull request #50
Opened 2023-07-19 19:24 UTC by chdinh

fix readme

2023-07-23 12:15 UTC, schote commented
Is this PR ready to review? Please don't forget to assign project and milestone

2023-07-23 15:25 UTC, chdinh commented
> Is this PR ready to review? Please don't forget to assign issue, project and milestone

Not yet.

2023-08-11 22:55 UTC, chdinh commented
@schote This PR is now ready to review. The current documentation can be found here: https://scanhub.brain-link.de/

Note: The documentation is currently only semi automatically build, i.e., the openapi.jsons need to be updated manually within the repositiory. This is done due to the fact that the patient manager is located in the UI backend and not in scanhub, which would have required a manual step in any case - the manual step is now at least consistent.

2023-08-14 11:50 UTC, schote requested changes

2023-08-14 11:50 UTC, schote commented on docs/Makefile
Do we also need to add licence information here?

2023-08-14 11:50 UTC, schote commented on docs/make.bat
Should we add licence information here?

2023-08-14 11:50 UTC, schote commented on docs/source/_openapi/device_openapi.json
This is the downloaded openapi file, correct? Since we only need this file temporary (to build the html for the documentation), I would suggest to add the downloaded json files to .gitignore. What do you think?

2023-08-14 11:50 UTC, schote commented on docs/source/_openapi/exam_openapi.json
See comment above

2023-08-14 11:50 UTC, schote commented on docs/source/_openapi/mri/acquisition_openapi.json
See comment above

2023-08-14 11:50 UTC, schote commented on docs/source/_openapi/mri/sequences_openapi.json
See comment above

2023-08-14 11:50 UTC, schote commented on docs/source/_openapi/ui_patient_manager_openapi.json
See comment above

2023-08-14 11:50 UTC, schote commented on docs/source/_openapi/workflow_openapi.json
See comment above

2023-08-14 11:50 UTC, schote commented on docs/source/conf.py
Licence?

2023-08-14 11:50 UTC, schote commented on docs/source/device_api.rst
Licence information? (Also applies to all the other `.rst` files)

2023-08-14 11:54 UTC, schote commented
> @schote This PR is now ready to review. The current documentation can be found here: https://scanhub.brain-link.de/
> 
> Note: The documentation is currently only semi automatically build, i.e., the openapi.jsons need to be updated manually within the repositiory. This is done due to the fact that the patient manager is located in the UI backend and not in scanhub, which would have required a manual step in any case - the manual step is now at least consistent.

@chdinh, but for this repository (scanhub) the openapi documentation is automatiacally deployed? This problem is only related to the separated repository (scanhub-ui)?

2023-08-20 09:07 UTC, chdinh commented on .github/workflows/docs.yml
> +      uses: actions/checkout@v2
thx - done

2023-08-20 09:07 UTC, chdinh commented on .github/workflows/docs.yml
> +      uses: actions/setup-python@v2
thx - done

2023-08-20 09:07 UTC, chdinh commented on .github/workflows/docs.yml
> +      - '*'
right - changed to main

2023-08-20 09:07 UTC, chdinh commented on docs/Makefile
done

2023-08-20 09:13 UTC, chdinh commented on docs/source/_openapi/mri/sequences_openapi.json
JSON is a data-only format. Comments are not allowed in JSON

2023-08-20 09:13 UTC, chdinh commented on docs/source/_openapi/ui_patient_manager_openapi.json
JSON is a data-only format. Comments are not allowed in JSON

2023-08-20 09:13 UTC, chdinh commented on docs/source/_openapi/workflow_openapi.json
JSON is a data-only format. Comments are not allowed in JSON

2023-08-20 09:13 UTC, chdinh commented on docs/source/conf.py
added - done

2023-08-20 09:17 UTC, chdinh commented on docs/source/device_api.rst
done

2023-08-20 09:17 UTC, chdinh commented on docs/make.bat
done

2023-08-20 16:37 UTC, schote approved these changes

2023-08-20 16:37 UTC, merged